version: "3.9"
   
services:
  db:
    image: mysql
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: MiPIS
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  django_gunicorn:
    volumes:
      - .:/project/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db