# Generated by Django 4.0.1 on 2022-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiPIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('picture', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
