# Generated by Django 4.0.1 on 2022-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiPIS', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='uid',
            field=models.CharField(default='345srd', max_length=6),
        ),
        migrations.AlterField(
            model_name='data',
            name='picture',
            field=models.ImageField(upload_to='MiPIS/files/images'),
        ),
    ]
