# Generated by Django 4.0.1 on 2022-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiPIS', '0003_data_uid_alter_data_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='uid',
        ),
        migrations.AlterField(
            model_name='data',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
