# Generated by Django 4.0.1 on 2022-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiPIS', '0005_data_accuracy_data_similiar_alter_data_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='found',
            field=models.BooleanField(default=False),
        ),
    ]
